language: node_js
node_js: node
deploy:
  provider: heroku
  api_key:
    secure: c/OPX0PMzhGu98e+p6x9urkJUEiLe+dWMB+72fUHsBhIm+3uWKfQvBCnsqUeIGZeMEy9aDntkKPxWSmObT7lVH9Y7WkPJypPBKAst4enwAdCQCHGqeqIky0FZ+EM382M4Xen3mNlYq0rSbtAPl0feQcwS0TpvqCWLUrzrp/tMqJMgZ5dQswVl/1JaLOns5m/1gLFurewq88gyf7HkqyCwbip+1ro8TS6nNI0Hvu8t/S6GNUN2ynV5m0uE63DOne+I+weK9rcamKtXpG/62yG4m6BmXrhVOcwntF0U2xevIbUgUZ1rHjlLoaPmtgyiOZpGjKQg+Ufojj5+x8HIxiGRtSFMeJWn9W4ejGZbvjrw49xbmYu+LTdGOkU6st96e8lsD9xW0l2xUticE3p2sHN+rvWZqgLhHUHHRgkZmY6Lw3AX5sKh8Vu2XplGVxEbBKyle3AZi5A4jBRNhiDyaCecF2GaOy/86TkT3EQUzTzeXj6EVOq6HTl/KpnHf8Ty+7MFdG9C3IjgHew6h8DRVLIUvbwSTkdSIZQe2ctu+BNYRTXzT0+JnXvoNdsNBVx/WOl2T1mGA4BER3uXXtzx6q6aRW3IWspbvIUZq3i80nmoqvQgmkRs9JpZ0Jg8INlI+1uecBfDgTfsdUi5rh768w52ETwrvOBRauYnR6m6VG/jdk=
  app: evening-hamlet-74118
  on:
    repo: Jollendi91/node-challenge-blog-api
